### ISSUE TITLE
Another Czech translations

### ISSUE THREAD

**Issue by martinlangcz** [eleanormurray/COVID_19#21]
[WaitingForCOVIDTestResults_Czech.pdf](https://github.com/eleanormurray/COVID_19/files/4361612/WaitingForCOVIDTestResults_Czech.pdf)
![WaitingForCOVIDTestResults_Czech](https://user-images.githubusercontent.com/41682965/77202247-3c9e7600-6aee-11ea-9822-d549861002af.jpg)
[PositiveCOVIDTest_Czech.pdf](https://github.com/eleanormurray/COVID_19/files/4361614/PositiveCOVIDTest_Czech.pdf)
![PositiveCOVIDTest_Czech](https://user-images.githubusercontent.com/41682965/77202250-3dcfa300-6aee-11ea-8cd5-c832b744b3e8.jpg)

**Comment by eleanormurray** [comment]
Thank you!!
