### ISSUE TITLE
Waiting/Positive Test Armenian Version

### ISSUE THREAD

**Issue by tavoundjian** [eleanormurray/COVID_19#23]
![WaitingForCOVIDTestResults_Armenian](https://user-images.githubusercontent.com/8933158/77279200-7a320900-6c7e-11ea-9745-c111b489f8a8.jpg)
![PositiveCOVIDTest_Armenian](https://user-images.githubusercontent.com/8933158/77279204-7aca9f80-6c7e-11ea-9e41-56786d2b5998.jpg)
[WaitingForCOVIDTestResults_Armenian.pdf](https://github.com/eleanormurray/COVID_19/files/4367098/WaitingForCOVIDTestResults_Armenian.pdf)
[PositiveCOVIDTest_Armenian.pdf](https://github.com/eleanormurray/COVID_19/files/4367099/PositiveCOVIDTest_Armenian.pdf)

**Comment by eleanormurray** [comment]
Thank you!
