### ISSUE TITLE
Waiting/ Positive Test_ German

### ISSUE THREAD

**Issue by AnjaKnoechel** [eleanormurray/COVID_19#24]
![WaitingForCOVIDTestResults_GermanInformal](https://user-images.githubusercontent.com/62542686/77303166-c0c14b00-6cf2-11ea-9257-604a46a3d7a3.jpg)
![WaitingForCOVIDTestResults_GermanFormal](https://user-images.githubusercontent.com/62542686/77303175-c3bc3b80-6cf2-11ea-9a2f-905243c21988.jpg)
![PositiveCOVIDTest_GermanInformal](https://user-images.githubusercontent.com/62542686/77303177-c454d200-6cf2-11ea-8b69-e4c6c3b5fb71.jpg)
![PositiveCOVIDTest_GermanFormal](https://user-images.githubusercontent.com/62542686/77303183-c6b72c00-6cf2-11ea-8d51-1681cd2e9fc0.jpg)

**Comment by eleanormurray** [comment]
Thank you!
