### ISSUE TITLE
updated files german version

### ISSUE THREAD

**Issue by AnjaKnoechel** [eleanormurray/COVID_19#25]
![WaitingForCOVIDTestResults_GermanFormal](https://user-images.githubusercontent.com/62542686/77368985-cb64fa00-6d5d-11ea-8c15-1cceaf208c11.jpg)
[WaitingForCOVIDTestResults_GermanInformal.pdf](https://github.com/eleanormurray/COVID_19/files/4372206/WaitingForCOVIDTestResults_GermanInformal.pdf)
![WaitingForCOVIDTestResults_GermanInformal](https://user-images.githubusercontent.com/62542686/77368991-cdc75400-6d5d-11ea-9c66-1fae67299c05.jpg)
[PositiveCOVIDTest_GermanFormal.pdf](https://github.com/eleanormurray/COVID_19/files/4372207/PositiveCOVIDTest_GermanFormal.pdf)
![PositiveCOVIDTest_GermanFormal](https://user-images.githubusercontent.com/62542686/77368994-cef88100-6d5d-11ea-8e2e-6a38c8f46673.jpg)
[PositiveCOVIDTest_GermanInformal.pdf](https://github.com/eleanormurray/COVID_19/files/4372208/PositiveCOVIDTest_GermanInformal.pdf)
![PositiveCOVIDTest_GermanInformal](https://user-images.githubusercontent.com/62542686/77368997-cf911780-6d5d-11ea-9117-8d642db354f8.jpg)
[WaitingForCOVIDTestResults_GermanFormal.pdf](https://github.com/eleanormurray/COVID_19/files/4372209/WaitingForCOVIDTestResults_GermanFormal.pdf)

**Comment by eleanormurray** [comment]
Thank you!
