### ISSUE TITLE
SickButNoTest_Bangla

### ISSUE THREAD

**Issue by jessicaislam** [eleanormurray/COVID_19#31]
[
![SickbutNoTest_bangla](https://user-images.githubusercontent.com/62347126/78285039-495b9a80-74ee-11ea-811b-41721e8edb97.jpg)
[SickbutNoTest_bangla.pdf](https://github.com/eleanormurray/COVID_19/files/4422958/SickbutNoTest_bangla.pdf)

](url)

**Comment by eleanormurray** [comment]
Thank you!
