### ISSUE TITLE
Translation in Tamil

### ISSUE THREAD

**Issue by AjayVells** [eleanormurray/COVID_19#32]
![(1) Poster](https://user-images.githubusercontent.com/63142266/78421855-b0a55600-7678-11ea-9a4c-fcdd65aabac0.jpg)
5 Tips for Everyone

**Comment by AjayVells** [comment]
![(2) Poster](https://user-images.githubusercontent.com/63142266/78421898-f6621e80-7678-11ea-92d8-2585d8ac1d5d.jpg)
What to do if you have been in contact with someone with known or suspected COVID-19

**Comment by AjayVells** [comment]
![(3) Poster](https://user-images.githubusercontent.com/63142266/78421920-2a3d4400-7679-11ea-92e4-a1df09f6c2cd.jpg)
What to do if someone you live with is sick with COVID-19

**Comment by AjayVells** [comment]
![(4) Poster](https://user-images.githubusercontent.com/63142266/78421936-522ca780-7679-11ea-8f46-bdfd1327b549.jpg)
What to do if you have tested positive for COVID-19

**Comment by AjayVells** [comment]
![(5) Poster](https://user-images.githubusercontent.com/63142266/78421950-74bec080-7679-11ea-9a1f-441c3cab3ba8.jpg)
What to do if you are feeling sick but haven't been (or can't get) tested

**Comment by AjayVells** [comment]
![(6) Poster](https://user-images.githubusercontent.com/63142266/78421963-915af880-7679-11ea-9445-ae1d4fe0ae22.jpg)
What to do if you are waiting for a COVID-19 test result

**Comment by eleanormurray** [comment]
Thank you!!
