### ISSUE TITLE
SickbutNoTest-spanish

### ISSUE THREAD

**Issue by iecastro** [eleanormurray/COVID_19#34]
Hi: it looked like this had not been translated to Spanish yet.

![SickbutNoTest-SPANISH](https://user-images.githubusercontent.com/41378681/78508046-f4b85980-7751-11ea-87dc-c9bca32117db.jpg)

**Comment by iecastro** [comment]
[SickbutNoTest-SPANISH.pptx](https://github.com/eleanormurray/COVID_19/files/4434621/SickbutNoTest-SPANISH.pptx)

**Comment by eleanormurray** [comment]
Thank you!
