### ISSUE TITLE
Hospitalized_French

### ISSUE THREAD

**Issue by bboutboul** [eleanormurray/COVID_19#35]
[Hospitalized_French.pptx](https://github.com/eleanormurray/COVID_19/files/4434987/Hospitalized_French.pptx)
![Hospitalized_French](https://user-images.githubusercontent.com/38542209/78511066-bd54a780-7767-11ea-9a3a-97db5c2ae3ee.jpg)
[Hospitalized_French.pdf](https://github.com/eleanormurray/COVID_19/files/4434988/Hospitalized_French.pdf)

**Comment by eleanormurray** [comment]
Thank you!
