### ISSUE TITLE
IfExposed_French

### ISSUE THREAD

**Issue by bboutboul** [eleanormurray/COVID_19#36]
![IfExposed_French](https://user-images.githubusercontent.com/38542209/78512521-31487d00-7773-11ea-823e-beb496edf7df.png)
[IfExposed_French.pptx](https://github.com/eleanormurray/COVID_19/files/4435237/IfExposed_French.pptx)
[IfExposed_French.pdf](https://github.com/eleanormurray/COVID_19/files/4435238/IfExposed_French.pdf)

**Comment by eleanormurray** [comment]
Thank you!
