### ISSUE TITLE
WaitingForCOVIDTestResults_French

### ISSUE THREAD

**Issue by bboutboul** [eleanormurray/COVID_19#41]
[WaitingForCOVIDTestResults_French.pdf](https://github.com/eleanormurray/COVID_19/files/4440123/WaitingForCOVIDTestResults_French.pdf)
[WaitingForCOVIDTestResults_French.pptx](https://github.com/eleanormurray/COVID_19/files/4440124/WaitingForCOVIDTestResults_French.pptx)
![WaitingForCOVIDTestResults_French](https://user-images.githubusercontent.com/38542209/78591903-28f34f00-7812-11ea-81dc-3703172cf8f3.jpg)

**Comment by eleanormurray** [comment]
Thank you!
