### ISSUE TITLE
SickNoTest_French

### ISSUE THREAD

**Issue by advdln** [eleanormurray/COVID_19#43]
![SickbutNoTest_French](https://user-images.githubusercontent.com/63222937/78603504-40d4ce00-7826-11ea-8c1d-551cb98afe8c.jpg)
[SickbutNoTest_French.pptx](https://github.com/eleanormurray/COVID_19/files/4440727/SickbutNoTest_French.pptx)

**Comment by eleanormurray** [comment]
Thank you!
