### ISSUE TITLE
PositiveCOVIDTest_Russian

### ISSUE THREAD

**Issue by bhoktum** [eleanormurray/COVID_19#44]
[PositiveCOVIDTest_Russian.jpg](https://user-images.githubusercontent.com/46426482/78808860-08eb9900-7994-11ea-9947-c89ffa58b24c.jpg)
[PositiveCOVIDTest_Russian.pdf](https://github.com/eleanormurray/COVID_19/files/4451623/PositiveCOVIDTest_Russian.pdf)

**Comment by eleanormurray** [comment]
Thank you!
