### ISSUE TITLE
SickbutNoTest_Russian

### ISSUE THREAD

**Issue by bhoktum** [eleanormurray/COVID_19#47]
[SickbutNoTest_Russian.jpg](https://user-images.githubusercontent.com/46426482/79074913-377fb180-7cbd-11ea-9f5c-11e255a8dbed.jpg)
[SickbutNoTest_Russian.pdf](https://github.com/eleanormurray/COVID_19/files/4466699/SickbutNoTest_Russian.pdf)

**Comment by eleanormurray** [comment]
Thank you!
