### ISSUE TITLE
WaitingforTests_Russian

### ISSUE THREAD

**Issue by bhoktum** [eleanormurray/COVID_19#48]
[WaitingForCOVIDTestResults_Russian.pdf](https://github.com/eleanormurray/COVID_19/files/4466703/WaitingForCOVIDTestResults_Russian.pdf)
[WaitingForCOVIDTestResults_Russian.jpg](https://user-images.githubusercontent.com/46426482/79074987-c12f7f00-7cbd-11ea-9934-461a889be11b.jpg)

**Comment by eleanormurray** [comment]
Thank you!
