### ISSUE TITLE
ExposedtoCovid_Russian

### ISSUE THREAD

**Issue by bhoktum** [eleanormurray/COVID_19#49]
[IfExposed_Russian.pdf](https://github.com/eleanormurray/COVID_19/files/4466724/IfExposed_Russian.pdf)
[IfExposed_Russian.jpg](https://user-images.githubusercontent.com/46426482/79075255-b675e980-7cbf-11ea-86db-e87340577b6d.jpg)

**Comment by eleanormurray** [comment]
Thank you!
