### ISSUE TITLE
Contact tracing spanish version

### ISSUE THREAD

**Issue by arebollon** [eleanormurray/COVID_19#53]
Hello, thank for sharing this amazing work. I am Arturo Rebollon, public health researcher in Panama.  We are working on contact tracing materials and translated this infographic in spanish. Hope it helps your team.   Keep the good work.

Arturo Rebollon, MD, MPH, CPH
email: arebollo@usf.edu

[ContactTracing_Spanish_revAR_06JUN2020.pptx](https://github.com/eleanormurray/COVID_19/files/4753287/ContactTracing_Spanish_revAR_06JUN2020.pptx)

**Comment by eleanormurray** [comment]
Thank you!
