### ISSUE TITLE
Persian

### ISSUE THREAD

**Issue by marziehg** [eleanormurray/COVID_19#8]
![5Tips_Persian](https://user-images.githubusercontent.com/1151596/77026986-667b5f80-696b-11ea-80f8-e4bdfc85ebe5.jpg)
[5Tips_Persian.pdf](https://github.com/eleanormurray/COVID_19/files/4352445/5Tips_Persian.pdf)
![5Tips_Persian](https://user-images.githubusercontent.com/1151596/77027047-9165b380-696b-11ea-93ab-5954f5978f34.png)

**Comment by eleanormurray** [comment]
Thank you!
